### ISSUE TITLE
test failed on master 4f051a4 on iMac

### ISSUE THREAD

**Issue by iamqk** [hughperkins/cuda-on-cl#14]
[ RUN      ] test_hostside_opencl_funcs.test_create_cl_kernel
Using Apple , OpenCL platform: Apple
Using OpenCL device: Iris Pro
building kernel myKernel
 ... built
hostdata[0] 0
/Volumes/Data/work/DeepLearning/tensorflow/tensorflow-cl/third_party/cuda-on-cl/test/gtest/test_hostside_opencl_funcs.cpp:55: Failure
Value of: hostdata[0]
  Actual: 0
Expected: 123.0f
Which is: 123
[  FAILED  ] test_hostside_opencl_funcs.test_create_cl_kernel (1087 ms)
[----------] 1 test from test_hostside_opencl_funcs (1087 ms total)

[----------] Global test environment tear-down
[==========] 57 tests from 9 test cases ran. (1139 ms total)
[  PASSED  ] 56 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] test_hostside_opencl_funcs.test_create_cl_kernel

**Comment by hughperkins** [comment]
Hmmm, the first thing you'd want to do is to track down where the bug is. ie, is it that the kernel fails to update the value in the gpu memory? Or is it that the copy from gpu to host fails to copy? or both work, but there's a race condition, and the program is reading the value before one or more of the operations have finished?

To answer these questions, one approach is to add opencl code inside the relevant cuda-on-cl functions, to eg dump the gpu memory at relevant points. You'll remove this code after fixing the bug, since it's problem-specific.

**Comment by hughperkins** [comment]
(Note that the travis mac tests pass https://travis-ci.org/hughperkins/cuda-on-cl/builds/218379031 . Unfortunately I do not have a Mac to dig into the problem myself...  On my own laptop I have an Intel HD5500 GPU, and all is working ok on that)

**Comment by hughperkins** [comment]
fixed in c9d684c, screenshot:
<img width="607" alt="screen shot 2017-04-29 at 7 23 49 pm" src="https://cloud.githubusercontent.com/assets/123560/25559849/c3fe5732-2d11-11e7-97b9-472205c434b2.png">
